// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvQCoV6nIQQEIp3my4sM42N4IqyGJL-9U',
    appId: '1:288972406645:android:85bacac8675cb267f79d3c',
    messagingSenderId: '288972406645',
    projectId: 'intakhib-b3a02',
    storageBucket: 'intakhib-b3a02.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDX3ZS9UIusz3dH-pU9Ux70vyAFsPdrmi4',
    appId: '1:288972406645:web:b94d890549319f4cf79d3c',
    messagingSenderId: '288972406645',
    projectId: 'intakhib-b3a02',
    authDomain: 'intakhib-b3a02.firebaseapp.com',
    storageBucket: 'intakhib-b3a02.appspot.com',
    measurementId: 'G-Z833DX89JD',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAFWFQgCZ93XdZN4qzGxjhw7sFJzUpO14Q',
    appId: '1:288972406645:ios:13f2a8a67295120ff79d3c',
    messagingSenderId: '288972406645',
    projectId: 'intakhib-b3a02',
    storageBucket: 'intakhib-b3a02.appspot.com',
    iosBundleId: 'org.example.mrtdeg',
  );

}